In [9]:
# Import the neccessary modules
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.ensemble import RandomForestClassifier

import warnings
warnings.filterwarnings('ignore')

In [10]:
path = 'cars_cleaned.csv'
df = pd.read_csv(path)
df

,name,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,2007,800.0,45000,Petrol
1,Mahindra Jeep CL550 MDI,2006,4250.0,40,Diesel
2,Hyundai Grand i10 Magna 1.2 Kappa VTVT,2014,3250.0,28000,Petrol
3,Ford EcoSport Titanium 1.5L TDCi,2014,5750.0,36000,Diesel
4,Ford Figo,2012,1750.0,41000,Diesel
...,...,...,...,...,...
812,Toyota Corolla Altis,2009,3000.0,132000,Petrol
813,Tata Zest XM Diesel,2018,2600.0,27000,Diesel
814,Mahindra Quanto C8,2013,3900.0,40000,Diesel
815,Honda Amaze 1.2 E i VTEC,2014,1800.0,50000,Petrol
816,Chevrolet Sail 1.2 LT ABS,2014,1600.0,50000,Petrol

In [11]:
df['brand'] = df['name'].str.split().str[0]
df = df.drop("name", axis=1)
df

     year   Price  kms_driven fuel_type      brand
0    2007   800.0       45000    Petrol    Hyundai
1    2006  4250.0          40    Diesel   Mahindra
2    2014  3250.0       28000    Petrol    Hyundai
3    2014  5750.0       36000    Diesel       Ford
4    2012  1750.0       41000    Diesel       Ford
..    ...     ...         ...       ...        ...
812  2009  3000.0      132000    Petrol     Toyota
813  2018  2600.0       27000    Diesel       Tata
814  2013  3900.0       40000    Diesel   Mahindra
815  2014  1800.0       50000    Petrol      Honda
816  2014  1600.0       50000    Petrol  Chevrolet

[817 rows x 5 columns]

In [12]:
#df = pd.get_dummies(df, columns= ["fuel_type", "brand"], dtype=int, drop_first=True)
#df

In [14]:
columns_to_ohe = ["fuel_type", "brand"]

OHE = ColumnTransformer([('ohe', OneHotEncoder(handle_unknown='ignore',drop='first'),columns_to_ohe )],
                        remainder='passthrough',  # Keep other columns unchanged
                        )

scaler = StandardScaler()
classifier = RandomForestClassifier(bootstrap=True,
                                    max_depth=80,
                                    max_features=2,
                                    min_samples_leaf=3,
                                    min_samples_split=8,
                                    n_estimators=100,
                                    )
#classifier = LogistiRegression()

In [15]:
model_pipe = Pipeline([
                        ('Preprocessing features', OHE),
                        ('Scaling and standardize data', scaler),
                        ('Classifier', classifier)
                        ])